package lyc.compiler;

import java_cup.runtime.*;
import lyc.compiler.files.IntermediateCodeGenerator;
import lyc.compiler.symbolTable.SymbolTableGenerator;
import java.util.Stack;

class Parser;
parser code {:
    private IntermediateCodeGenerator intermediateCode = IntermediateCodeGenerator.getInstance();
    private Stack<String> pilaInit = new Stack<>();
    private Stack<Integer> pilaWhile = new Stack<>();
    private Stack<Integer> pilaIf = new Stack<>();
    private Stack<Integer> pilaElse = new Stack<>();
    //private Stack<Integer> pilaContador = new Stack<>();
    private boolean banderaPila = false;
    private Stack<String> banderaCondicion = new Stack<>();
    private Stack<Integer> pilaCond = new Stack<>();
    private Stack<String> pilaExpresion = new Stack<>();
    private Stack<String> pilaCmp = new Stack<>();
    private Stack<String> pilaCmpNeg = new Stack<>();
    private Stack<Integer> pilaSaltos = new Stack<>();
    private SymbolTableGenerator symbolTable = SymbolTableGenerator.getInstance();
    private String cmpAux = "";
    private String cmpAuxNeg = "";
    private String tipoDatoAux = "";
    private String variableNegCalc = "";
    private boolean orInit = false;
:};

// Terminals
terminal NUMERAL;
terminal INCLUDE;
terminal PUNTO;
terminal INTEGER;
terminal FLOAT;
terminal STRING;
terminal MAIN;
terminal ELSE;
terminal CORCH_ABRE;
terminal CORCH_CIERRA;
terminal ASIGNACION;
terminal PUNTO_COMA;
terminal SYS_OUT;
terminal SYS_IN;
terminal AND;
terminal OR;
terminal POINTER;
terminal BARRA;
terminal ASTERISCO;
terminal SALTO_LINEA;
terminal COMENTARIO_MULTI;
terminal COMENTARIO_SINGLE;
terminal CADENA;
terminal READ;
terminal WRITE;

terminal CTE;
terminal ID;
terminal OP_SUM;
terminal OP_MUL;
terminal OP_RES;
terminal OP_DIV;
terminal PA;
terminal PC;
terminal IF;
terminal WHILE;
terminal COMA;
terminal DISTINTO;
terminal NEGADO;
terminal IGUAL_IGUAL;
terminal MENOR_IGUAL;
terminal MAYOR_IGUAL;
terminal MENOR;
terminal MAYOR;
terminal LLA;
terminal LLC;
terminal CTE_REAL;
terminal INIT;
terminal SLICEANDCONCAT;
terminal NEGCALCULATION;
terminal DP;

// Non Terminals
non terminal inicial;
non terminal programa;
non terminal sentencia;
non terminal asignacion;
non terminal expresion;
non terminal factor;
non terminal termino;
non terminal ifHeader;
non terminal seleccion;
non terminal condicion;
non terminal comparacion;
non terminal comparador;
non terminal iteracion;
non terminal read;
non terminal write;
non terminal bloque_init;
non terminal decs;
non terminal dec;
non terminal listaId;
non terminal tipoDato;
non terminal listaExpresiones;
non terminal listaSlice;
non terminal sliceArg;
non terminal restoSliceArgs;
non terminal variableNegCalc;
// Start Symbol Definition
start with inicial;

inicial  ::=  bloque_init programa;
inicial  ::=         ;

programa ::= programa sentencia {: System.out.println("programa => programa sentencia"); :};
programa ::= sentencia {: System.out.println("programa => sentencia"); :};

sentencia ::= asignacion {: System.out.println("sentencia => asignacion"); :};
sentencia ::= seleccion {: System.out.println("sentencia => seleccion"); :};
sentencia ::= iteracion {: System.out.println("sentencia => seleccion"); :};

asignacion ::= ID:id {: symbolTable.verifyType(id.toString()); :} ASIGNACION expresion {:
    Integer intA = intermediateCode.addTerceto("=", id.toString(), intermediateCode.getIndexDraw("Eind"));
    intermediateCode.addIndex("Aind", intA);
    System.out.println("asignacion => id asignacion expresion;");
:};

iteracion 	::= 	 WHILE:_while {: banderaPila  = false; intermediateCode.addTerceto("ADDLABEL", "_", "_"); :} PA condicion PC LLA programa LLC {:
    //intermediateCode.addTerceto("BI", intermediateCode.getIndexDraw("Condind"), "_");
    intermediateCode.addTerceto("BI", "["+pilaCond.pop()+"]", "_");

    Integer intFin = intermediateCode.getNextIndex();

    intermediateCode.getTercetoByIdx(pilaWhile.pop()).modificarTerceto("["+intFin+"]");

    System.out.println("WHILE:_while PA condicion PC LLA programa LLC");
 :};

ifHeader    ::= 	IF {: banderaPila  = true; :} PA condicion PC {:
    System.out.println("IF PA condicion PC");
 :};

seleccion	::=		ifHeader LLA programa LLC {:
    // apilo idTerceto cuando encuentro { y desapilo y modifico el terceto cuando encuentro una }
            Integer intFin = intermediateCode.getNextIndex();
            //intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
            System.out.println("TERCETO FINAL SALTO: -- " + intFin);
            String auxCondicion = banderaCondicion.pop();
            System.out.println(auxCondicion);
            if(auxCondicion.equals("AND")){
                //for(Integer cont=pilaContador.pop();cont>0;cont--){
                    intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                    intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                //}
            }
            else if(auxCondicion.equals("OR")){
                //pilaContador.pop();
                Integer segSalto = pilaIf.pop();
                intermediateCode.getTercetoByIdx(segSalto).modificarTerceto("["+intFin+"]");
                intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+(segSalto+1)+"]");
                System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAA  ---------------"+segSalto);
            }
            else if(auxCondicion.equals("simple")){
                //pilaContador.pop();
                intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                //intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+(segSalto-1)+"]");
            }
            pilaCond.pop(); // para desapilar la cond que me quedo en la pila si es que tengo WHILE e IF anidados
    System.out.println("ifHeader LLA programa LLC");
 :};

seleccion	::= 	ifHeader LLA programa  LLC {:
                Integer intFin = intermediateCode.addTerceto("BI","_","_");
                pilaElse.push(intFin);
                intFin++;
                //intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                System.out.println("TERCETO FINAL SALTO: -- " + intFin);
                String auxCondicion = banderaCondicion.pop();
                System.out.println(auxCondicion);
                if(auxCondicion.equals("AND")){
                    //for(Integer cont=pilaContador.pop();cont>0;cont--){
                        intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                        intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                    //}
                }
                else if(auxCondicion.equals("OR")){
                    //pilaContador.pop();
                    Integer segSalto = pilaIf.pop();
                    intermediateCode.getTercetoByIdx(segSalto).modificarTerceto("["+intFin+"]");
                    intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+(segSalto+1)+"]");
                    System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAA  ---------------"+segSalto);
                }
                else if(auxCondicion.equals("simple")){
                    //pilaContador.pop();
                    intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+intFin+"]");
                    //intermediateCode.getTercetoByIdx(pilaIf.pop()).modificarTerceto("["+(segSalto-1)+"]");
                }
                pilaCond.pop();
 :}
 ELSE LLA programa LLC {:
    Integer intFin = intermediateCode.getNextIndex();
     intermediateCode.getTercetoByIdx(pilaElse.pop()).modificarTerceto("["+intFin+"]");

System.out.println("ifHeader LLA programa LLC ELSE LLA programa LLC");
:};

condicion 	::= 	comparacion AND:op comparacion {:

    //modifco segundo salto
    intermediateCode.getTercetoByIdx(pilaSaltos.pop()).modificarSaltoTerceto(pilaCmp.pop());
    pilaCmpNeg.pop();
    //modifico primer salto
    intermediateCode.getTercetoByIdx(pilaSaltos.pop()).modificarSaltoTerceto(pilaCmp.pop());
    pilaCmpNeg.pop();

    Integer tercetoNum = intermediateCode.getIndex("Cmpind");
    intermediateCode.addIndex("Condind", tercetoNum);

    //pilaContador.push(1);
    banderaCondicion.push("AND");

    pilaCond.push(intermediateCode.getIndex("Condind"));


    //System.out.println("SF1: ----> "+ saltoFalso1 + "-----------SF2: ----> " + saltoFalso2 + "-----------idFinal: ----> " + idFinal );
    System.out.println("comparacion AND:op comparacion");
:};

condicion 	::= comparacion OR:op comparacion  {:

        //desapilo pilaSaltos
        //modificoSaltoTerceto(pilaSaltos,pilaAux.pop)
           intermediateCode.getTercetoByIdx(pilaSaltos.pop()).modificarSaltoTerceto(pilaCmp.pop());
           pilaCmpNeg.pop();
        //desapilo pilaSaltos
        // modificoSaltoTerceto(pilaSaltos,pilaAuxNeg.pop)
        intermediateCode.getTercetoByIdx(pilaSaltos.pop()).modificarSaltoTerceto(pilaCmpNeg.pop());
        pilaCmp.pop();

    Integer tercetoNum = intermediateCode.getIndex("Cmpind");
        intermediateCode.addIndex("Condind", tercetoNum);

        //pilaContador.push(true);
        banderaCondicion.push("OR");

        pilaCond.push(intermediateCode.getIndex("Condind"));
    System.out.println("comparacion OR:op comparacion");
:};

condicion	::= 	comparacion 				   {:
    Integer tercetoNum = intermediateCode.getIndex("Cmpind");
    intermediateCode.addIndex("Condind", tercetoNum);

    intermediateCode.getTercetoByIdx(pilaSaltos.pop()).modificarSaltoTerceto(pilaCmp.pop());
    pilaCmpNeg.pop();
    //pilaContador.push(false);
    banderaCondicion.push("simple");

    pilaCond.push(intermediateCode.getIndex("Condind"));

    System.out.println("comparacion");
:};

condicion 	::=		NEGADO comparacion			   {: System.out.println("NEGADO condicion"); :};
condicion	::= 	NEGADO expresion 			   {: System.out.println("NEGADO expresion"); :};

comparacion ::= 	expresion {: pilaExpresion.push(intermediateCode.getIndexDraw("Eind")); :} comparador expresion  {:
    Integer intCmp = intermediateCode.addTerceto("cmp",pilaExpresion.pop(),intermediateCode.getIndexDraw("Eind"));
    intermediateCode.addIndex("Cmpind",intCmp);

    //creo terceto salto     id=intermediateCode.addTerceto("_","_","_");
    Integer intSalto = intermediateCode.addTerceto("_","_","_");
    // apilo tercetoCreado   (pilaSaltos.push(id))
    pilaSaltos.push(intSalto);
    // pregunto si es if o while, si if pilaIf.push(id) ----- si while pilaWhile.push(id)


    /*if(orInit){
      intSalto = intermediateCode.addTerceto(cmpAuxNeg,"_","_");
      orInit = false;
    }
    else {
      intSalto = intermediateCode.addTerceto(cmpAux,"_","_");
    }*/

    if (banderaPila){
        pilaIf.push(intSalto);
    }
    else {
        pilaWhile.push(intSalto);
    }
    System.out.println("expresion comparador expresion");
:};

comparador  ::= 	IGUAL_IGUAL:comp 				{:
    //cmpAux = "BNE";
    //cmpAuxNeg = "BEQ";
    pilaCmp.push("BNE");
    pilaCmpNeg.push("BEQ");
    System.out.println("IGUAL_IGUAL:comp");
:};
comparador  ::= 	DISTINTO:comp 					{:
    cmpAux = "BEQ";
    cmpAuxNeg = "BNE";
    System.out.println("DISTINTO:comp");
 :};
comparador  ::= 	MAYOR_IGUAL:comp 				{:
    cmpAux = "BLT";
    cmpAuxNeg = "BGE";
    System.out.println("MAYOR_IGUAL:comp"); :};
comparador  ::= 	MENOR_IGUAL:comp				{:
    pilaCmp.push("BGT");
    pilaCmpNeg.push("BLE");
    System.out.println("MENOR_IGUAL:comp"); :};
comparador  ::= 	MAYOR:comp						{:
    cmpAux = "BLE";
    cmpAuxNeg = "BGT";
    System.out.println("MAYOR:comp"); :};
comparador  ::= 	MENOR:comp						{:
    pilaCmp.push("BGE");
    pilaCmpNeg.push("BLT");
    System.out.println("MENOR:comp"); :};

expresion ::= expresion OP_SUM factor {:
    Integer intE = intermediateCode.addTerceto("+", intermediateCode.getIndexDraw("Eind"), intermediateCode.getIndexDraw("Find")); // (+,[2],[4])
    intermediateCode.addIndex("Eind", intE);
    System.out.println("expresion SUMA factor");
:};
expresion ::= expresion OP_RES factor {:
    Integer intE = intermediateCode.addTerceto("-", intermediateCode.getIndexDraw("Eind"), intermediateCode.getIndexDraw("Find"));
    intermediateCode.addIndex("Eind", intE);
    System.out.println("expresion RESTA factor");
:};
expresion ::= factor {:
    Integer tercetoNum = intermediateCode.getIndex("Find");
    intermediateCode.addIndex("Eind", tercetoNum);
    System.out.println("expresion => factor");
:};

factor    ::= factor OP_MUL termino {:
    Integer intF = intermediateCode.addTerceto("*", intermediateCode.getIndexDraw("Find"), intermediateCode.getIndexDraw("Tind"));
    intermediateCode.addIndex("Find", intF);
    System.out.println("factor MULTI termino");
:};
factor    ::= factor OP_DIV termino {:
    Integer intF = intermediateCode.addTerceto("/", intermediateCode.getIndexDraw("Find"), intermediateCode.getIndexDraw("Tind"));
    intermediateCode.addIndex("Find", intF);
    System.out.println("factor DIV termino");
:};
factor    ::= termino {:
    Integer tercetoNum = intermediateCode.getIndex("Tind");
    intermediateCode.addIndex("Find", tercetoNum);
    System.out.println("factor => termino");
:};

termino   ::= CTE:cte {:
    Integer intT = intermediateCode.addTerceto(cte.toString(), "_", "_");
    intermediateCode.addIndex("Tind", intT);
    System.out.println("CONSTANTE");
:};
termino   ::= ID:id {:
    Integer intT = intermediateCode.addTerceto(id.toString(), "_", "_");
    intermediateCode.addIndex("Tind", intT);
    System.out.println("IDENTIFICADOR");
:};
termino   ::= CTE_REAL:cte {:
     Integer intT = intermediateCode.addTerceto(cte.toString(), "_", "_");
     intermediateCode.addIndex("Tind", intT);
     System.out.println("CONSTANTE REAL");
:};
termino   ::= CADENA:cadena {:
    Integer intT = intermediateCode.addTerceto(cadena.toString(), "_", "_");
    intermediateCode.addIndex("Tind", intT);
    System.out.println("CADENA");
:};
termino   ::= PA expresion PC {:
    System.out.println("( expresion )");
:};

//E-S
sentencia ::= read {:
    Integer tercetoNum = intermediateCode.getIndex("Rind");
    intermediateCode.addIndex("Sind", tercetoNum);
    System.out.println("INICIO READ");
:};

read    ::= SYS_IN PA ID:id {: symbolTable.verifyType(id.toString()); :} PC {:
    int Rind = intermediateCode.addTerceto("read", id.toString(), "_");
    intermediateCode.addIndex("Rind", Rind);
    System.out.println("READ");
:};

sentencia ::= write {:
    Integer tercetoNum = intermediateCode.getIndex("Wind");
    intermediateCode.addIndex("Sind", tercetoNum);
    System.out.println("INICIO WRITE");
:};

write   ::= SYS_OUT PA ID:id {: symbolTable.verifyType(id.toString()); :} PC {:
    int Wind = intermediateCode.addTerceto("write", id.toString(), "_");
    intermediateCode.addIndex("Wind", Wind);
    System.out.println("WRITE");
:};
write   ::= SYS_OUT PA CADENA:cadena PC {:
    int Wind = intermediateCode.addTerceto("write", cadena.toString(), "_");
    intermediateCode.addIndex("Wind", Wind);
    System.out.println("WRITE");
:};

//SLICEANDCONCAT
termino ::= SLICEANDCONCAT PA CTE:inicio COMA CTE:fin COMA CADENA:palabra1 COMA CADENA:palabra2 COMA CTE:concatenar PC {:
    symbolTable.addToken("@resSC", "string");
    intermediateCode.addTerceto("=", "@resSC", "\"\"");

    symbolTable.addToken("@resParcial", "string");
    intermediateCode.addTerceto("=", "@resParcial", "\"\"");

    symbolTable.addToken("@subcadena", "string");
    intermediateCode.addTerceto("=", "@subcadena", "\"\"");

    symbolTable.addToken("@auxIni", "int");
    intermediateCode.addTerceto("=", "@auxIni", inicio.toString());

    symbolTable.addToken("@auxFin", "int");
    intermediateCode.addTerceto("=", "@auxFin", fin.toString());

    symbolTable.addToken("@auxPal1", "string");
    intermediateCode.addTerceto("=", "@auxPal1", palabra1.toString());

    symbolTable.addToken("@auxPal2", "string");
    intermediateCode.addTerceto("=", "@auxPal2", palabra2.toString());

    symbolTable.addToken("@auxConcat", "int");
    intermediateCode.addTerceto("=", "@auxConcat", concatenar.toString());

    int cmp = intermediateCode.addTerceto("CMP", "@auxConcat", "1");
    intermediateCode.addTerceto("BNE", "[" + (cmp + 8)  + "]", "_");

    int limites = intermediateCode.addTerceto("@auxIni", "@auxFin", "_");
    int corte = intermediateCode.addTerceto("SUBSTRING", "@auxPal1", "[" + limites + "]");
    intermediateCode.addTerceto("=", "@subcadena", "[" + corte + "]");
    int concat = intermediateCode.addTerceto("CONCAT", "@auxPal2", "@subcadena");
    int finResParcial = intermediateCode.addTerceto("=", "@resParcial", "[" + concat + "]");
    intermediateCode.addTerceto("BI", "["+ (finResParcial + 7) +"]", "_");

    int limites2 = intermediateCode.addTerceto("@auxIni", "@auxFin", "_");
    int corte2 = intermediateCode.addTerceto("SUBSTRING", "@auxPal2", "[" + limites2 + "]");
    intermediateCode.addTerceto("=", "@subcadena", "[" + corte2 + "]");
    int concat2 = intermediateCode.addTerceto("CONCAT", "@auxPal1", "@subcadena");
    int finResParcial2 = intermediateCode.addTerceto("=", "@resParcial", "[" + concat2 + "]");

    int auxRes  = intermediateCode.addTerceto("=", "@resSC", "@resParcial");
    intermediateCode.addIndex("Tind", auxRes);

    System.out.println("termino => SLICEANDCONCAT PA CTE COMA CTE COMA CADENA COMA CADENA COMA CTE PC");
:};

//NEGCALCULATION
termino ::= NEGCALCULATION PA listaExpresiones PC {:
    int mod = intermediateCode.addTerceto("MOD", "@contNeg", "2");
    int cmp = intermediateCode.addTerceto("CMP", "[" + mod +"]", "0");
    intermediateCode.addTerceto("BNE", "[" + (cmp + 4)  +"]", "_");
    int auxResP = intermediateCode.addTerceto("=", "@aux", "@sumaParcial");
    intermediateCode.addTerceto("BI", "[" + (auxResP + 3)  +"]", "_");
    intermediateCode.addTerceto("=", "@aux", "@mulParcial");

    int auxRes  = intermediateCode.addTerceto("=", "@res", "@aux");
    intermediateCode.addIndex("Tind", auxRes);

    System.out.println("termino => NEGCALCULATION PA listaExpresiones PC");
:};
listaExpresiones ::= listaExpresiones COMA variableNegCalc {:
    intermediateCode.addTerceto("=", "@aux", variableNegCalc);
    int cmp = intermediateCode.addTerceto("CMP", "@aux", "0");
    intermediateCode.addTerceto("BGE", "[" + (cmp + 8)  +"]", "_");

    int sumaAux = intermediateCode.addTerceto("+", "@contNeg", "1");
    intermediateCode.addTerceto("=", "@contNeg", "[" + sumaAux +"]");

    int sumaPAux = intermediateCode.addTerceto("+", "@sumaParcial", "@aux");
    intermediateCode.addTerceto("=", "@sumaParcial", "[" + sumaPAux +"]");

    int mulPAux = intermediateCode.addTerceto("*", "@mulParcial", "@aux");
    intermediateCode.addTerceto("=", "@mulParcial", "[" + mulPAux +"]");

    System.out.println("listaExpresiones => listaExpresiones COMA expresion");
:};
listaExpresiones ::= variableNegCalc {:
    symbolTable.addToken("@contNeg", "int");
    intermediateCode.addTerceto("=", "@contNeg", "0");
    symbolTable.addToken("@res", "int");
    intermediateCode.addTerceto("=", "@res", "0");
    symbolTable.addToken("@sumaParcial", "int");
    intermediateCode.addTerceto("=", "@sumaParcial", "0");
    symbolTable.addToken("@mulParcial", "int");
    intermediateCode.addTerceto("=", "@mulParcial", "1");
    symbolTable.addToken("@aux", "int");
    intermediateCode.addTerceto("=", "@aux", variableNegCalc);
    int cmp = intermediateCode.addTerceto("CMP", "@aux", "0");
    intermediateCode.addTerceto("BGE", "[" + (cmp + 8)  +"]", "_");

    int sumaAux = intermediateCode.addTerceto("+", "@contNeg", "1");
    intermediateCode.addTerceto("=", "@contNeg", "[" + sumaAux +"]");

    int sumaPAux = intermediateCode.addTerceto("+", "@sumaParcial", "@aux");
    intermediateCode.addTerceto("=", "@sumaParcial", "[" + sumaPAux +"]");

    int mulPAux = intermediateCode.addTerceto("*", "@mulParcial", "@aux");
    intermediateCode.addTerceto("=", "@mulParcial", "[" + mulPAux +"]");

    System.out.println("listaExpresiones => expresion");
:};

variableNegCalc ::= CTE:cte {: variableNegCalc = cte.toString(); :};
variableNegCalc ::= CTE_REAL:cte_real {: variableNegCalc = cte_real.toString(); :};
variableNegCalc ::= ID:id {: variableNegCalc = id.toString();  :};

//INIT - Declaracion de variables
bloque_init ::= INIT LLA decs LLC {:
    System.out.println("bloque_init => INIT LLA decs LLC");
:};

decs ::= decs dec {: System.out.println("decs => decs dec"); :};
decs ::= dec {: System.out.println("decs => dec"); :};
dec ::= listaId DP tipoDato:tp {:
    while (!pilaInit.isEmpty()) {
        String variable = pilaInit.pop();
        symbolTable.addDataType(variable, tipoDatoAux);
    }
    System.out.println("dec => listaId DP tipoDato");
:};

listaId ::= listaId COMA ID:id {:
    pilaInit.push(id.toString());
    System.out.println("listaId => listaId COMA ID");
:};
listaId ::= ID:id {:
    pilaInit.push(id.toString());
    System.out.println("listaId => ID");
:};

tipoDato ::= FLOAT:decimal {:
    tipoDatoAux = decimal.toString();
    System.out.println("tipoDato => float");
:};
tipoDato ::= INTEGER:entero {:
    tipoDatoAux = entero.toString();
    System.out.println("tipoDato => int");
:};
tipoDato ::= STRING:string {:
    tipoDatoAux = string.toString();
    System.out.println("tipoDato => string");
:};
