package lyc.compiler;

import java_cup.runtime.*;
import lyc.compiler.files.*;

class Parser;
parser code {:
    private IntermediateCodeGenerator intermediateCode = IntermediateCodeGenerator.getInstance();
:};

// Terminals
terminal NUMERAL;
terminal INCLUDE;
terminal PUNTO;
terminal INTEGER;
terminal FLOAT;
terminal STRING;
terminal MAIN;
terminal ELSE;
terminal CORCH_ABRE;
terminal CORCH_CIERRA;
terminal ASIGNACION;
terminal PUNTO_COMA;
terminal SYS_OUT;
terminal SYS_IN;
terminal AND;
terminal OR;
terminal POINTER;
terminal BARRA;
terminal ASTERISCO;
terminal SALTO_LINEA;
terminal COMENTARIO_MULTI;
terminal COMENTARIO_SINGLE;
terminal CADENA;
terminal READ;
terminal WRITE;

terminal CTE;
terminal ID;
terminal OP_SUM;
terminal OP_MUL;
terminal OP_RES;
terminal OP_DIV;
terminal PA;
terminal PC;
terminal IF;
terminal WHILE;
terminal COMA;
terminal DISTINTO;
terminal NEGADO;
terminal IGUAL_IGUAL;
terminal MENOR_IGUAL;
terminal MAYOR_IGUAL;
terminal MENOR;
terminal MAYOR;
terminal LLA;
terminal LLC;
terminal CTE_REAL;
terminal INIT;
terminal SLICEANDCONCAT;
terminal NEGCALCULATION;
terminal DP;

// Non Terminals
non terminal inicial;
non terminal programa;
non terminal sentencia;
non terminal asignacion;
non terminal expresion;
non terminal factor;
non terminal termino;
non terminal ifHeader;
non terminal seleccion;
non terminal condicion;
non terminal comparacion;
non terminal comparador;
non terminal iteracion;
non terminal read;
non terminal write;
non terminal bloque_init;
non terminal decs;
non terminal dec;
non terminal listaId;
non terminal tipoDato;
non terminal listaExpresiones;
non terminal listaSlice;
non terminal sliceArg;
non terminal restoSliceArgs;

// Start Symbol Definition
start with inicial;

inicial  ::=  programa;
inicial  ::=         ;

programa ::= programa sentencia {: System.out.println("programa => programa sentencia"); :};
programa ::= sentencia {: System.out.println("programa => sentencia"); :};

sentencia ::= asignacion {: System.out.println("sentencia => asignacion"); :};
sentencia ::= seleccion {: System.out.println("sentencia => seleccion"); :};
sentencia ::= iteracion {: System.out.println("sentencia => seleccion"); :};


asignacion ::= ID ASIGNACION expresion{: System.out.println("asignacion => id asignacion expresion"); :};

asignacion ::= ID:id ASIGNACION expresion PUNTO_COMA {:
    Integer intA = intermediateCode.addTerceto("=", id.toString(), intermediateCode.getIndexDraw("Eind"));
    intermediateCode.addIndex("Aind", intA);
    System.out.println("asignacion => id asignacion expresion;");
:};

iteracion 	::= 	WHILE:_while PA condicion PC LLA programa LLC {: System.out.println("WHILE:_while PA condicion PC LLA programa LLC"); :};
ifHeader   ::= 	IF PA condicion PC {: System.out.println("IF PA condicion PC"); :};

seleccion	::=		ifHeader LLA programa LLC {: System.out.println("ifHeader LLA programa LLC"); :};
seleccion	::= 	ifHeader LLA programa LLC ELSE LLA programa LLC {: System.out.println("ifHeader LLA programa LLC ELSE LLA programa LLC"); :};

condicion 	::= 	comparacion AND:op comparacion {: System.out.println("comparacion AND:op comparacion"); :};
condicion 	::= 	comparacion OR:op comparacion  {: System.out.println("comparacion OR:op comparacion"); :};
condicion	::= 	comparacion 				   {: System.out.println("comparacion"); :};

condicion 	::=		NEGADO comparacion			   {: System.out.println("NEGADO condicion"); :};
condicion	::= 	NEGADO expresion 			   {: System.out.println("NEGADO expresion"); :};

comparacion ::= 	expresion comparador expresion  {: System.out.println("expresion comparador expresion"); :};
comparador  ::= 	IGUAL_IGUAL:comp 				{: System.out.println("IGUAL_IGUAL:comp"); :};
comparador  ::= 	DISTINTO:comp 					{: System.out.println("DISTINTO:comp"); :};
comparador  ::= 	MAYOR_IGUAL:comp 				{: System.out.println("MAYOR_IGUAL:comp"); :};
comparador  ::= 	MENOR_IGUAL:comp				{: System.out.println("MENOR_IGUAL:comp"); :};
comparador  ::= 	MAYOR:comp						{: System.out.println("MAYOR:comp"); :};
comparador  ::= 	MENOR:comp						{: System.out.println("MENOR:comp"); :};

expresion ::= expresion OP_SUM factor {:
    Integer intE = intermediateCode.addTerceto("+", intermediateCode.getIndexDraw("Eind"), intermediateCode.getIndexDraw("Find"));
    intermediateCode.addIndex("Eind", intE);
    System.out.println("expresion SUMA factor");
:};
expresion ::= expresion OP_RES factor {:
    Integer intE = intermediateCode.addTerceto("-", intermediateCode.getIndexDraw("Eind"), intermediateCode.getIndexDraw("Find"));
    intermediateCode.addIndex("Eind", intE);
    System.out.println("expresion RESTA factor");
:};
expresion ::= factor {:
    Integer tercetoNum = intermediateCode.getIndex("Find");
    System.out.println("El valor que tiene Find es: " + tercetoNum);
    intermediateCode.addIndex("Eind", tercetoNum);
    System.out.println("expresion => factor");
:};

factor    ::= factor OP_MUL termino {:
    Integer intF = intermediateCode.addTerceto("*", intermediateCode.getIndexDraw("Find"), intermediateCode.getIndexDraw("Tind"));
    intermediateCode.addIndex("Find", intF);
    System.out.println("factor MULTI termino");
:};
factor    ::= factor OP_DIV termino {:
    Integer intF = intermediateCode.addTerceto("/", intermediateCode.getIndexDraw("Find"), intermediateCode.getIndexDraw("Tind"));
    intermediateCode.addIndex("Find", intF);
    System.out.println("factor DIV termino");
:};
factor    ::= termino {:
    Integer tercetoNum = intermediateCode.getIndex("Tind");
    intermediateCode.addIndex("Find", tercetoNum);
    System.out.println("factor => termino");
:};

termino   ::= CTE:cte {:
    Integer intT = intermediateCode.addTerceto(cte.toString(), "_", "_");
    System.out.println("Voy a poner en Tind: " + intT);
    intermediateCode.addIndex("Tind", intT);
    System.out.println("CONSTANTE");
:};
termino   ::= ID:id {:
    Integer intT = intermediateCode.addTerceto(id.toString(), "_", "_");
    System.out.println("Voy a poner en Tind: " + intT);
    intermediateCode.addIndex("Tind", intT);
    System.out.println("IDENTIFICADOR");
:};
termino   ::= CTE_REAL:cte {: System.out.println("CONSTANTE REAL"); :};
termino   ::= PA expresion PC {: System.out.println("( expresion )"); :};
termino   ::= CADENA:cadena {: System.out.println("CADENA"); :};

//E-S
sentencia ::= read {: System.out.println("INICIO READ"); :};
read    ::= SYS_IN PA ID PC {: System.out.println("READ"); :};
sentencia ::= write {: System.out.println("INICIO WRITE"); :};
write   ::= SYS_OUT PA ID PC {: System.out.println("WRITE"); :};
write   ::= SYS_OUT PA CADENA PC {: System.out.println("WRITE"); :};

//SLICEANDCONCAT
termino ::= SLICEANDCONCAT PA CTE COMA CTE COMA CADENA COMA CADENA COMA CTE PC {: System.out.println("termino => SLICEANDCONCAT PA CTE COMA CTE COMA CADENA COMA CADENA COMA CTE PC"); :};

//NEGCALCULATION
termino ::= NEGCALCULATION PA listaExpresiones PC {: System.out.println("termino => NEGCALCULATION PA listaExpresiones PC"); :};
listaExpresiones ::= listaExpresiones COMA expresion {: System.out.println("listaExpresiones => listaExpresiones COMA expresion"); :};
listaExpresiones ::= expresion {: System.out.println("listaExpresiones => expresion"); :};

//INIT - Declaracion de variables
bloque_init ::= INIT LLA decs LLC{: System.out.println("bloque_init => INIT LLA decs LLC"); :};
listaId ::= listaId COMA ID {: System.out.println("listaId => listaId COM ID"); :};
listaId ::= ID {: System.out.println("listaId => ID"); :};

decs ::= decs dec {: System.out.println("decs => decs dec"); :};
decs ::= dec{: System.out.println("decs => dec"); :};
dec ::= listaId DP tipoDato {: System.out.println("dec => listaId DP tipoDato"); :};

tipoDato ::= FLOAT {: System.out.println("tipoDato => float"); :};
tipoDato ::= INTEGER {: System.out.println("tipoDato => int"); :};
tipoDato ::= STRING {: System.out.println("tipoDato => string"); :};
